site_name: 课程资料
nav:
  - 首页: index.md
  - Python 程序设计: python.md
  - Python 程序设计:
      - 课程概述: python/introduction.md
      - 基本概念: python/basic.md
      - 数据类型基础: python/data-types-basic.md
      - 程序结构: python/control-flow.md
      - 数据类型进阶: python/data-types-advanced.md
      - 输入输出: python/io-file.md
      - 文件与目录: python/file-and-path.md
      - 模块与包: python/lib-and-packages.md
      - 第三方库与虚拟环境: python/virtualenvs.md
      - 函数进阶与类: python/class.md
  - 计算机安全与维护: cms.md
  - 计算机安全与维护:
      - 课件: cms/slides.md
      - Windows 安装实验: cms/windows-install-homework.md
      - Windows 组件实验: cms/windows-components.md
      - 恶意代码实验: cms/malware.md
      - 数据恢复实验: cms/data-recovery-homework.md
      - 脚本实验: cms/scripts-homework.md
  - 网页设计与制作: web.md
  - 网页设计与制作:
      - 作业: web/homework.md
      - 课程概述: web/introduction.md
      - HTML 元素详解: web/html-elements.md
      - CSS 样式表: web/css-first-steps.md
      - CSS 文本样式: web/css-text.md
      - CSS 盒子样式: web/css-box.md
      - CSS 布局: web/css-layout.md
      - JavaScript 初探: web/javascript-introduction.md
      - JavaScript 基础: web/javascript-basic.md
      - JavaScript 结构化代码: web/javascript-blocks.md
      - 面向对象的 JavaScript: web/javascript-oo.md
      - JavaScript API: web/javascript-API.md
      - Bootstrap: web/bootstrap.md
      - jQuery: web/jQuery.md
  - 数字媒体安全应用与实践: apdms.md
  - 数字媒体安全应用与实践:
      - 课程概述: apdms/introduction.md
      - Flask 简介: apdms/flask-intro.md
      - Flask 初探: apdms/flask-getting-start.md
      - Jinja2 模板: apdms/jinja2.md
      - WTForms 表单: apdms/wtforms.md

# Repository
repo_name: "anjingcuc/courses-wiki"
repo_url: "https://github.com/anjingcuc/courses-wiki"

theme:
  name: null
  custom_dir: "material"
  language: "zh"
  palette:
    primary: "white"
    accent: "red"
  logo:
    icon: "school"
  feature:
    tabs: true
  font:
    text: "Fira Sans"
    code: "Fira Mono"

markdown_extensions:
  - codehilite:
      linenums: true
